baseurl         = "/"
theme           = "casper-two"
languageCode    = "en-UK"
disqusShortname = ""
paginate        = 6

[params]
  title       = "Nikos Voulgaris | Blog"
  subtitle    = "Challenge everything"

  cover       = "img/blog-cover.jpg"
  description = "Nikos Voulgaris blog"
  metaDescription = "Nikos Voulgaris blog"
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "nivoul"
  githubName = "nvoulgaris"

  logo = "hugo-logo.png"
  orgName = "EM"
  orgWebsite = "https://www.telematika.org"
  orgDescription = "Here is a description placeholder for your org"

  author = "Nikos Voulgaris"
  authorAvatar = "img/nv_author_icon.jpg"
  authorLocation = "Athens, GR"
  authorWebsite = "https://nvoulgaris.com"
  authorDescription = "Challenge everything"

  pageNotFoundTitle = "404 - Page not found"

  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 240

[[menu.main]]
  name = "Tags"
  url = "/tags"
  weight = 230

[[menu.main]]
  name = "About Me"
  url = "/about"
  weight = 220

[[menu.main]]
  name = "Contact"
  url = "/contact"
  weight = 210
