disqusShortname: nvoulgaris-com
module:
  imports:
    - path: github.com/CaiJimmy/hugo-theme-stack/v3

languageCode: en-us
title: Nikos Voulgaris
copyright: Nikos Voulgaris

pagination:
  pagerSize: 7

params:
  sidebar:
    subtitle: Challenge everything
    avatar:
      enabled: true
      local: false
      src: ../../img/nv_author_icon.jpg
  rssFullContent: true
  favicon: /favicon.ico
  article:
    headingAnchor: false
  headingAnchor: false
  widgets:
    homepage:
      - type: search
      - type: tag-cloud
      - type: udemy-course
        params:
          limit: 12
      - type: archives
    page:
      - type: search
      - type: toc
      - type: udemy-course
      - type: tag-cloud
        params:
          limit: 10
  udemy:
    title: "TDD in Action with AI:"
    subtitle: From Fundamentals to Production
    description: Confidently apply Test-Driven Development in real-world codebases — and integrate AI tools to boost your productivity without sacrificing control.
    image: ../../img/tdd_udemy_course_image.png
    link: https://www.udemy.com/course/tdd-in-action-with-ai-from-fundamentals-to-production/?referralCode=959DC15A77B4BD968C3C
    linkText: View on Udemy
  colorScheme:
    toggle: true
    default: auto
  footer:
    since: 2018
  comments:
    enabled: true
    provider: disqus
    disqusShortname: nvoulgaris-com

services:
    googleAnalytics:
        id: G-7643KK7Q6D

permalinks:
    post: /:slug/
    page: /:slug/

menu: 
  main:
    - name: Home
      url: /
      weight: -90
      params:
        icon: home
    - name: Search
      url: /search
      weight: -80
      params: 
        icon: search
    - name: About Me
      url: /about-me
      weight: -70
      params:
        icon: user
    - name: Tags
      url: /tags
      weight: -60
      params:
        icon: tag
    - name: My course
      url: /test-driven-development-in-action-with-ai
      weight: -50
      params:
        icon: link
    - name: Books
      url: /books
      weight: -40
      params:
        icon: archives
    - name: Contact
      url: /contact
      weight: -30
      params:
        icon: messages
  social:
    - name: Github
      url: https://github.com/nvoulgaris
      weight: -40
      params:
        icon: brand-github
    - name: Twitter
      url: https://twitter.com/nivoul
      weight: -30
      params:
        icon: brand-twitter
    - name: LinkedIn
      url: https://www.linkedin.com/in/nikos-voulgaris-44455546
      weight: -20
