baseurl         = "/"
theme           = "casper-two"
languageCode    = "en-UK"
paginate        = 6
Copyright       = "All rights reserved - 2019"

[params]
  title       = "Nikos Voulgaris"
  subtitle    = "Challenge everything"

  cover       = "img/blog-cover.jpg"
  description = "Nikos Voulgaris blog"
  metaDescription = "Nikos Voulgaris blog"
  googleAnalytics = "UA-114060129-1"
  customCSS = []
  RSSLink = ""

  twitterName = "nivoul"
  githubName = "nvoulgaris"
  linkedinName = "nikos-voulgaris-44455546"

  logo = ""
  orgName = "EM"
  orgWebsite = "https://www.telematika.org"
  orgDescription = "Here is a description placeholder for your org"

  author = "Nikos Voulgaris"
  authorAvatar = "img/nv_author_icon.jpg"
  authorLocation = "Athens, GR"
  authorWebsite = "https://nvoulgaris.com"
  authorDescription = "Challenge everything"

  pageNotFoundTitle = "404 - Page not found"

  singleViewStyle = "casper"
  disqusShortname = "nvoulgaris-com"

  hideHUGOSupport = false
  hjsStyle = "default"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 250

[[menu.main]]
  name = "About Me"
  url = "/about"
  weight = 240

[[menu.main]]
  name = "Tags"
  url = "/tags"
  weight = 230

[[menu.main]]
  name = "Books"
  url = "/books"
  weight = 220

[[menu.main]]
  name = "Contact"
  url = "/contact"
  weight = 210
